name: test-fast-ctc-decode

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - name: Test binding
        run: |
          python3 -m pip install maturin
          make test
	  