name: test-fast-ctc-decode

on: [push]

jobs:

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Test ${{ matrix.os }} binding
        run: |
          python3 -m venv venv3
          source venv3/bin/activate
          python3 -m pip install maturin numpy
          maturin develop
          cargo test
          python3 tests/test_decode.py
